/**
 * This file generated by PlannerFw's Preprocessor
 * 
 * Version    0.0.1
 * Author     W3plan
 * Category   Preprocessor
 * Copyright  Copyright 2015-2016 W3plan, http://w3plan.net
 * Licenses   GNU GPLv3 license <http://www.gnu.org/copyleft/gpl.html>
 */
/* PlannerFw Template */
function pfTemp(pfDataSet, planner) {
var _pf19edb768 = '';_pf19edb768 += '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /><title>PlannerFw + PHP CodeIgniter Application</title><link href="/css/style.css" rel="stylesheet" type="text/css" /></head><body><div class="content"><h1>'; _pf19edb768 += pfDataSet.title; _pf19edb768 += '</h1><div class="data"><table><tr><td width="30%">ID</td><td>'; _pf19edb768 += pfDataSet.person.id; _pf19edb768 += '</td></tr><tr><td valign="top">Name</td><td>'; _pf19edb768 += pfDataSet.person.name; _pf19edb768 += '</td></tr><tr><td valign="top">Gender</td><td> '; if (pfDataSet.person.gender.toUpperCase() == "M") {
_pf19edb768 += "Male"; } else {
_pf19edb768 += "Female"; }
_pf19edb768 += ' </td></tr><tr><td valign="top">Date of birth (yyyy-mm-dd)</td><td>'; _pf19edb768 += pfDataSet.person.dob; _pf19edb768 += '</td></tr></table></div><br> '; _pf19edb768 += pfDataSet.link_back; _pf19edb768 += ' </div></body></html>';
return _pf19edb768;
}