/**
 * This file generated by PlannerFw's Preprocessor
 * 
 * Version    0.0.1
 * Author     W3plan
 * Category   Preprocessor
 * Copyright  Copyright 2015-2016 W3plan, http://w3plan.net
 * Licenses   GNU GPLv3 license <http://www.gnu.org/copyleft/gpl.html>
 */
/* PlannerFw Template */
function pfTemp(pfDataSet, planner) {
var _pf19edb768 = '';_pf19edb768 += '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /><title>PlannerFw + PHP CodeIgniter Application</title><link href="/css/style.css" rel="stylesheet" type="text/css" /><link href="/css/calendar.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="/js/calendar.js"></script></head><body><div class="content"><h1>'; _pf19edb768 += pfDataSet.title; _pf19edb768 += '</h1> '; _pf19edb768 += pfDataSet.message; _pf19edb768 += ' <form method="post" action="'; _pf19edb768 += pfDataSet.action; _pf19edb768 += '"><div class="data"><table><tr><td width="30%">ID</td><td><input type="text" name="id" disabled="disable" class="text" value="'; _pf19edb768 += pfDataSet.id; _pf19edb768 += '"/></td><input type="hidden" name="id" value="'; _pf19edb768 += pfDataSet.id; _pf19edb768 += '"/></tr><tr><td valign="top">Name<span style="color:red;">*</span></td><td><input type="text" name="name" class="text" value="'; _pf19edb768 += pfDataSet.name; _pf19edb768 += '"/></td></tr><tr><td valign="top">Gender<span style="color:red;">*</span></td><td> '; if (pfDataSet.gender.toUpperCase() == "M") {
_pf19edb768 += '<input type="radio" name="gender" value="M" checked="checked"/> Male' + '<input type="radio" name="gender" value="F" /> Female'; } else {
_pf19edb768 += '<input type="radio" name="gender" value="M" /> Male' + '<input type="radio" name="gender" value="F" checked="checked"/> Female'; }
_pf19edb768 += ' </td></tr><tr><td valign="top">Date of birth (dd-mm-yyyy)<span style="color:red;">*</span></td><td><input type="text" name="dob" onclick="displayDatePicker(\'dob\');" class="text" value="'; _pf19edb768 += pfDataSet.dob; _pf19edb768 += '"/><a href="javascript:void(0);" onclick="displayDatePicker(\'dob\');"><img src="/images/calendar.png" alt="calendar" class="iconpos" border="0"></a></td></tr><tr><td>&nbsp;</td><td><input type="submit" value="Save"/></td></tr></table></div></form><br /> '; _pf19edb768 += pfDataSet.link_back; _pf19edb768 += ' </div></body></html>';
return _pf19edb768;
}