/**
 * This file generated by PlannerFw's Preprocessor
 * 
 * Version    0.0.1
 * Author     W3plan
 * Category   Preprocessor
 * Copyright  Copyright 2015-2016 W3plan, http://w3plan.net
 * Licenses   GNU GPLv3 license <http://www.gnu.org/copyleft/gpl.html>
 */
/* PlannerFw Template */
function pfTemp(pfDataSet, planner) {
var _pf19edb768 = '';_pf19edb768 += '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /><title>PlannerFw + PHP CodeIgniter Application</title><link href="/css/style.css" rel="stylesheet" type="text/css" /></head><body><div class="content"><h1>PlannerFw + PHP CodeIgniter Application</h1><div class="paging"> '; _pf19edb768 += pfDataSet.pagination; _pf19edb768 += ' </div><div class="data"> '; _pf19edb768 += '<table border="0" cellpadding="4" cellspacing="0">' + "<thead><tr>" + "<th>No</th><th>Name</th><th>Gender</th><th>Date of Birth (yyyy-mm-dd)</th><th>Operations</th>" + "</tr></thead><tbody>"; for (i = 0; i < pfDataSet.persons.length; i++) {
_pf19edb768 += '<tr><td>' + pfDataSet.persons[i]['id'] + '</td>' + '<td>' + pfDataSet.persons[i]['name'] + '</td>'; if (pfDataSet.persons[i]['gender'].toUpperCase() == "M") {
_pf19edb768 += "<td>Male</td>"; } else {
_pf19edb768 += "<td>Female</td>"; }
_pf19edb768 += /* * Using String.fromCharCode(39) to output ' */ '<td>' + pfDataSet.persons[i]['dob'] + '</td>' + '<td>' + '<a href="/person/view/' + pfDataSet.persons[i]['id'] + '" class="view">view</a>' + '<a href="/person/update/' + pfDataSet.persons[i]['id'] + '" class="update">update</a>' + '<a href="/person/delete/' + pfDataSet.persons[i]['id'] + '" class="delete" onclick="return confirm(' + String.fromCharCode(39) + 'Are you sure want to delete this person?' + String.fromCharCode(39) + ')">delete</a>' + "</td></tr>"; }
_pf19edb768 += "</tbody>" + "</table>"; _pf19edb768 += ' </div><br><a href="/person/add" class="add">add new data</a></div></body></html> ';
return _pf19edb768;
}